In [1]:
import cv2
import numpy as np

In [2]:
image = cv2.imread("new.jpg")
M = np.ones(image.shape,dtype="uint8") *165

add = cv2.add(image,M)

In [4]:
cv2.imshow("add",add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
subtract = cv2.subtract(image,M)
cv2.imshow("subtract",subtract)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
print(M)

[[[165 165 165]
  [165 165 165]
  [165 165 165]
  ...
  [165 165 165]
  [165 165 165]
  [165 165 165]]

 [[165 165 165]
  [165 165 165]
  [165 165 165]
  ...
  [165 165 165]
  [165 165 165]
  [165 165 165]]

 [[165 165 165]
  [165 165 165]
  [165 165 165]
  ...
  [165 165 165]
  [165 165 165]
  [165 165 165]]

 ...

 [[165 165 165]
  [165 165 165]
  [165 165 165]
  ...
  [165 165 165]
  [165 165 165]
  [165 165 165]]

 [[165 165 165]
  [165 165 165]
  [165 165 165]
  ...
  [165 165 165]
  [165 165 165]
  [165 165 165]]

 [[165 165 165]
  [165 165 165]
  [165 165 165]
  ...
  [165 165 165]
  [165 165 165]
  [165 165 165]]]


In [7]:
print(add)

[[[255 255 226]
  [255 255 226]
  [255 255 227]
  ...
  [255 255 165]
  [255 255 165]
  [255 255 165]]

 [[255 255 228]
  [255 255 228]
  [255 255 229]
  ...
  [255 255 166]
  [255 255 166]
  [255 255 166]]

 [[255 255 230]
  [255 255 230]
  [255 255 230]
  ...
  [255 255 167]
  [255 255 167]
  [255 255 167]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [8]:
print(subtract)

[[[12  0  0]
  [12  0  0]
  [13  0  0]
  ...
  [ 8  0  0]
  [ 8  0  0]
  [ 6  0  0]]

 [[14  0  0]
  [14  0  0]
  [16  0  0]
  ...
  [ 9  0  0]
  [ 9  0  0]
  [ 7  0  0]]

 [[17  0  0]
  [17  0  0]
  [17  0  0]
  ...
  [10  0  0]
  [10  0  0]
  [ 8  0  0]]

 ...

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]]
